/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as KoleksiTerbaruRouteImport } from './routes/koleksi-terbaru'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as PesananOrderNumberRouteImport } from './routes/pesanan.$orderNumber'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const KoleksiTerbaruRoute = KoleksiTerbaruRouteImport.update({
  id: '/koleksi-terbaru',
  path: '/koleksi-terbaru',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananOrderNumberRoute = PesananOrderNumberRouteImport.update({
  id: '/pesanan/$orderNumber',
  path: '/pesanan/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/koleksi-terbaru': typeof KoleksiTerbaruRoute
  '/tentang': typeof TentangRoute
  '/pesanan/$orderNumber': typeof PesananOrderNumberRoute
  '/produk/$slug': typeof ProdukSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/koleksi-terbaru': typeof KoleksiTerbaruRoute
  '/tentang': typeof TentangRoute
  '/pesanan/$orderNumber': typeof PesananOrderNumberRoute
  '/produk/$slug': typeof ProdukSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/koleksi-terbaru': typeof KoleksiTerbaruRoute
  '/tentang': typeof TentangRoute
  '/pesanan/$orderNumber': typeof PesananOrderNumberRoute
  '/produk/$slug': typeof ProdukSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/katalog'
    | '/keranjang'
    | '/koleksi-terbaru'
    | '/tentang'
    | '/pesanan/$orderNumber'
    | '/produk/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/katalog'
    | '/keranjang'
    | '/koleksi-terbaru'
    | '/tentang'
    | '/pesanan/$orderNumber'
    | '/produk/$slug'
  id:
    | '__root__'
    | '/'
    | '/katalog'
    | '/keranjang'
    | '/koleksi-terbaru'
    | '/tentang'
    | '/pesanan/$orderNumber'
    | '/produk/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KatalogRoute: typeof KatalogRoute
  KeranjangRoute: typeof KeranjangRoute
  KoleksiTerbaruRoute: typeof KoleksiTerbaruRoute
  TentangRoute: typeof TentangRoute
  PesananOrderNumberRoute: typeof PesananOrderNumberRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koleksi-terbaru': {
      id: '/koleksi-terbaru'
      path: '/koleksi-terbaru'
      fullPath: '/koleksi-terbaru'
      preLoaderRoute: typeof KoleksiTerbaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/$orderNumber': {
      id: '/pesanan/$orderNumber'
      path: '/pesanan/$orderNumber'
      fullPath: '/pesanan/$orderNumber'
      preLoaderRoute: typeof PesananOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KatalogRoute: KatalogRoute,
  KeranjangRoute: KeranjangRoute,
  KoleksiTerbaruRoute: KoleksiTerbaruRoute,
  TentangRoute: TentangRoute,
  PesananOrderNumberRoute: PesananOrderNumberRoute,
  ProdukSlugRoute: ProdukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
